server:
  port: 10086
spring:
  application:
    name: xuriven-eureka #应用名称，会在Eureka中显示

eureka:
  client:
    service-url: #EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其他server地址
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 5000 #剔除无效连接的间隔时间
    enable-self-preservation: false #关闭自我保护状态

